### ISSUE TITLE
HTTP 500 ERROR

### ISSUE THREAD

**Issue by thysmichels** [wkennedy/swagger4spring-web-example#1]
I am using your example and made some changes and want to know why the following is happening:

When I use postman and hit:
http://localhost:8080/swagger4springweb-example/api/v1/account/?Name=Swaggit3

I get the correct result. When I do exactly the same in Swagger UI I get an Error 500 that says that no value has been sent in Name. Even when I change required=true it still happens.

Any suggestions. 

My code looks like:

@ApiOperation(value = "Create a account using Param", notes = "Creates a new account in salesforce using Param", httpMethod = "POST")
    @ApiError(code = 500, reason = "Process error")
    @RequestMapping(method = RequestMethod.POST, produces = "application/json")
    public @ResponseBody String createAccountFromParamName(@ApiParam(internalDescription = "java.lang.string", value="string", name = "Name", required = false) String Name) 
    {  
        Account newAccount = new Account();
        newAccount.setName(Name);
        String id = api.createSObject("Account", newAccount);
        return "{id:" + id +"}";
    }

**Comment by wkennedy** [comment]
Hey there, it looks like you are missing @RequestParam for Name.  @ApiParam is used only for Swagger, but Spring still needs @RequestParam, so it will look like this:

```
 @ApiParam(internalDescription = "java.lang.string", value="string", name = "Name", required = false) 
 @RequestParam(required = true) String Name
```

**Comment by thysmichels** [comment]
Thanks I did try it and now I get a Error 400:
The request sent by the client was syntactically incorrect.

I can successfully curl the url like this:
http://localhost:8080/swagger4springweb-example/api/v1/account/?Name=Swaggit4
and get:
{id:001g0000004343SAAQ}

Which is the correct response back. Do I maybe need to config something in documentation.jsp javascript to enable a feature?

**Comment by wkennedy** [comment]
I was able to recreate the problem you are seeing.  A fix has been checked in to swagger4spring-web and will be resolved in version 0.1.5.  Thanks for the help!

**Comment by thysmichels** [comment]
Great thanks, any idea when version 0.1.5 will be released?

**Comment by wkennedy** [comment]
I'll try to push out a new version tonight and post a comment here when it is available in Maven central.

**Comment by wkennedy** [comment]
The latest version 0.1.5 is available now.

**Comment by thysmichels** [comment]
Thanks Will that worked for me!
